version: "3.7"

services:
    db:
        restart: "no"

    api:
        image: openmrs/openmrs-platform:${TAG:-dev}
        build:
            target: dev
            context: .
        restart: "no"
        ports:
            - "8080:8080"
            - "8000:8000"
        environment:
            OMRS_DEV_DEBUG_PORT: ${OMRS_DEV_DEBUG_PORT:-8000}
        volumes:
            - ~/.m2:/root/.m2
            - ./:/openmrs_distro
