version: "3.7"

services:
    db:
        image: mariadb:10.3
        command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
        healthcheck:
            test: "mysql --user=${OMRS_DB_USER:-openmrs} --password=${OMRS_DB_PASSWORD:-openmrs} --execute \"SHOW DATABASES;\""
            interval: 3s
            timeout: 1s
            retries: 5
        environment:
            MYSQL_DATABASE: openmrs
            MYSQL_USER: ${OPENMRS_DB_USER:-openmrs}
            MYSQL_PASSWORD: ${OPENMRS_DB_PASSWORD:-openmrs}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-openmrs}
        volumes:
            - db-data:/var/lib/mysql

    api:
        image: openmrs/openmrs-platform:${TAG:-2.5.x-nightly}
        depends_on:
            - db
        build: .
        ports:
            - "8080:8080"
        environment:
            OMRS_MODULE_WEB_ADMIN: "true"
            OMRS_AUTO_UPDATE_DATABASE: "true"
            OMRS_CREATE_TABLES: "true"

            OMRS_DB_HOSTNAME: db
            OMRS_DB_NAME: ${OMRS_DB_NAME:-openmrs}
            OMRS_DB_USERNAME: ${OMRS_DB_USERNAME:-openmrs}
            OMRS_DB_PASSWORD: ${OMRS_DB_PASSWORD:-openmrs}
            OMRS_ADMIN_USER_PASSWORD: ${OMRS_ADMIN_USER_PASSWORD-Admin123}
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs"]
            timeout: 5s
        volumes:
            - openmrs-data:/openmrs/data/

volumes:
    db-data:
    openmrs-data:
